#pragma once

// FILE AUTOGENERATED. DO NOT CHANGE THIS FILE

#include "players/alvaro_garcia.h"
#include "players/arthur_tadier.h"
#include "players/cesar_perales.h"
#include "players/ericbiagioli_firstfree.h"
#include "players/ericbiagioli_incorrectmoves.h"
#include "players/juan_diego_castro.h"
#include "players/luis_izaguirre.h"
#include "players/melanie_cortez.h"
#include "players/melisa_rivera.h"
#include "players/roger_huauya.h"
